https://github.com/mwodka2/Malory Wodka/blob/master/_config.ymltitle:

mwodka2.github.io/blob/master/_config.ymltitle: Malory Wodka # your name (or website title) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
  <a href="https://www.linkedin.com/in/malory-wodka-33844b232/">View My LinkedIn Profile</a> 
  <br><br>
  Specializations and Courses
  <br><br>
  <a href="https://coursera.org/share/3c68f7692dce2772fbd870c3094c7d55">Google Data Analytics Certification by Google on Coursera: 4 Courses</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
